kafka:
  # Use KRaft mode (no Zookeeper)
  kraft:
    enabled: true

  # Replicas
  controller:
    replicaCount: 1

  broker:
    replicaCount: 1

  # Resource limits for dev
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # Listeners
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT

  # Persistence
  persistence:
    enabled: true
    size: 10Gi

  # Auto-create topics
  autoCreateTopicsEnable: true

  # Log retention
  logRetentionHours: 24
  logRetentionBytes: 1073741824

  # Default replication factors
  defaultReplicationFactor: 1
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  transactionStateLogMinIsr: 1

  # Number of partitions for auto-created topics
  numPartitions: 3

  # Pre-create required topics
  provisioning:
    enabled: true
    topics:
      - name: events
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "86400000"
          segment.bytes: "1073741824"
      - name: alerts
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "86400000"
          segment.bytes: "1073741824"
