apiVersion: v2
name: grafana
description: Grafana for visualizing device alerts
type: application
version: 1.0.0
appVersion: "10.2.0"

dependencies:
  - name: grafana
    version: 7.0.8
    repository: https://grafana.github.io/helm-charts
