grafana:
  # Admin credentials
  adminUser: admin
  adminPassword: admin_qa_password

  # Service configuration
  service:
    type: ClusterIP
    port: 80

  # Resource limits
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

  # Persistence
  persistence:
    enabled: true
    size: 10Gi

  # Datasources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: TimescaleDB
          type: postgres
          url: timescaledb-qa-timescaledb:5432
          database: monitoring
          user: monitor_user
          secureJsonData:
            password: monitor_qa_password
          jsonData:
            sslmode: disable
            postgresVersion: 1500
            timescaledb: true
          isDefault: true
          editable: true

  # Dashboard providers
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  # Dashboards
  dashboardsConfigMaps:
    default: "grafana-qa-dashboards"

  # Grafana config
  grafana.ini:
    server:
      root_url: "http://grafana-qa.example.com"
