services:
  # Kafka with KRaft mode (no Zookeeper)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Topic settings
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Kafka topic creation
  kafka-setup:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic events --partitions 3 --replication-factor 1
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic alerts --partitions 1 --replication-factor 1
        echo 'Topics created successfully'
      "

  # Flink JobManager
  jobmanager:
    image: flink:1.18.1-java21
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 1600m
        taskmanager.memory.process.size: 1600m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2
        execution.checkpointing.interval: 10s
        execution.checkpointing.mode: EXACTLY_ONCE
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ./monitor/target/monitor-1.0.0.jar:/opt/flink/usrlib/monitor.jar
      - flink_data:/tmp/flink-checkpoints

  # Flink TaskManager
  taskmanager:
    image: flink:1.18.1-java21
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 1600m
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./monitor/target/monitor-1.0.0.jar:/opt/flink/usrlib/monitor.jar
      - flink_data:/tmp/flink-checkpoints

volumes:
  kafka_data:
    driver: local
  flink_data:
    driver: local
