apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vector
  labels:
    app: vector
spec:
  type: ClusterIP
  ports:
  - port: 8686
    targetPort: 8686
    name: api
  selector:
    app: vector
