apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flink-config
  labels:
    app: flink
    component: config
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: {{ .Release.Name }}-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.memory.process.size: {{ .Values.jobmanager.memory }}
    taskmanager.memory.process.size: {{ .Values.taskmanager.memory }}
    taskmanager.numberOfTaskSlots: {{ .Values.taskmanager.taskSlots }}
    parallelism.default: {{ .Values.parallelism }}

    # Checkpointing
    execution.checkpointing.interval: 10s
    execution.checkpointing.mode: EXACTLY_ONCE
    execution.checkpointing.min-pause: 5s
    execution.checkpointing.timeout: 60s
    state.backend: filesystem
    state.checkpoints.dir: {{ .Values.checkpoint.dir }}
    state.savepoints.dir: {{ .Values.checkpoint.dir }}/savepoints

    # High availability (production only)
    {{- if eq .Values.environment "prod" }}
    high-availability: kubernetes
    high-availability.storageDir: {{ .Values.checkpoint.dir }}/ha
    {{- end }}

    # REST API
    rest.port: 8081
    rest.address: {{ .Release.Name }}-jobmanager

  log4j-console.properties: |+
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender

    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

    logger.flink.name = org.apache.flink
    logger.flink.level = INFO

    logger.kafka.name = org.apache.kafka
    logger.kafka.level = WARN
