apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jobmanager
  labels:
    app: flink
    component: jobmanager
spec:
  type: {{ .Values.jobmanager.service.type }}
  ports:
  - name: rpc
    port: 6123
    targetPort: 6123
  - name: blob-server
    port: 6124
    targetPort: 6124
  - name: webui
    port: 8081
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager
