apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-flink
  labels:
    app: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-flink
  labels:
    app: flink
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-flink
  labels:
    app: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-flink
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-flink
